version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: gosen-dev-db
    environment:
      POSTGRES_DB: gosen_dev
      POSTGRES_USER: gosen
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - gosen-dev-network

  web:
    build: .
    container_name: gosen-dev-web
    command: gunicorn gosen_project.wsgi:application --bind 0.0.0.0:8000 --workers 2 --timeout 120
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    ports:
      - "8082:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - TELEGRAM_BOT_TOKEN=8713051023:AAGRv9wIwO9Doln2DMczN5om0acqosj64t0
      - TELEGRAM_CHAT_ID=1646298746
      - POSTGRES_DB=gosen_dev
      - POSTGRES_USER=gosen
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    networks:
      - gosen-dev-network

volumes:
  postgres_data_dev:
  static_volume:
  media_volume:

networks:
  gosen-dev-network:
    driver: bridge
